# Generated by Django 4.2.1 on 2023-05-18 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Admin",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=20)),
                ("contrasenia", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Insumos",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("seccion", models.CharField(max_length=45)),
                ("nombre", models.CharField(max_length=20)),
                ("precio_compra", models.IntegerField()),
                ("stock", models.IntegerField()),
                ("categoria", models.CharField(max_length=20)),
                ("fecha_vencimiento", models.DateField()),
                ("fecha_ingreso", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Productos",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("seccion", models.CharField(max_length=45)),
                ("nombre", models.CharField(max_length=20)),
                ("precio_venta", models.IntegerField()),
                ("stock", models.IntegerField()),
                ("categoria", models.CharField(max_length=20)),
                ("fecha_fabricacion", models.DateField()),
                ("fecha_vencimiento", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Proveedores",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=20)),
                ("telefono", models.IntegerField()),
                ("correo", models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name="Ventas",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("cantidad", models.SmallIntegerField()),
                ("total", models.IntegerField()),
                (
                    "idproducto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="MeLateApp.productos",
                    ),
                ),
            ],
        ),
    ]
