# Generated by Django 4.2.1 on 2023-05-20 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MeLateApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="proveedores",
            name="observaciones",
            field=models.CharField(default="Nulo", max_length=45),
            preserve_default=False,
        ),
    ]
