# Generated by Django 4.2.1 on 2023-05-20 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MeLateApp", "0002_proveedores_observaciones"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proveedores",
            name="nombre",
            field=models.CharField(max_length=45),
        ),
    ]
