# Generated by Django 4.2.1 on 2023-05-20 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MeLateApp", "0003_alter_proveedores_nombre"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proveedores",
            name="correo",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="proveedores",
            name="nombre",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="proveedores",
            name="observaciones",
            field=models.CharField(max_length=100),
        ),
    ]
