# Generated by Django 4.2.1 on 2023-05-21 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "MeLateApp",
            "0005_alter_proveedores_correo_alter_proveedores_nombre_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="insumos",
            name="unidad_medida",
            field=models.CharField(default="", max_length=20),
            preserve_default=False,
        ),
    ]
