# Generated by Django 4.2.1 on 2023-05-21 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MeLateApp", "0006_insumos_unidad_medida"),
    ]

    operations = [
        migrations.RemoveField(model_name="insumos", name="categoria",),
        migrations.AddField(
            model_name="insumos",
            name="proveedor",
            field=models.CharField(default="", max_length=45),
            preserve_default=False,
        ),
    ]
