# Generated by Django 4.2.1 on 2023-05-23 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MeLateApp", "0008_rename_nombre_admin_usuario"),
    ]

    operations = [
        migrations.RemoveField(model_name="ventas", name="idproducto",),
        migrations.AddField(
            model_name="ventas",
            name="productos",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
    ]
