# Generated by Django 4.2.1 on 2023-05-23 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MeLateApp", "0009_remove_ventas_idproducto_ventas_productos"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ventas", name="cantidad", field=models.CharField(max_length=50),
        ),
    ]
